# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a136d60199339bc6deb346825232b2320d077afc140bf331114dd22768da44facece8f93c4b650980c1034b994fbbdfa3b248611f226be4ac75c5ef0595c452

test:
  secret_key_base: 07e59a292b91709f283f1eb840c73c3b8ecc5b2e29a7af44fc7e9914f8d16bafdb2a5b493dff5b06716353fc78e374c10e44099e1d4a917a423312a0fdc2d22c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
